version: '3'
services: 
  geoserver:
    #image: 'geotekne/geoserver:lime-alpine-2.16.2'
    image: 'geotekne/geoserver:lime-buster-2.16.2'
    hostname: geoserver
    env_file:
      - ./geoserver.env
    ports:
      - "8080:8080"
    volumes:
      #- './data/geoserver/data_dir/:/var/local/geoserver'
      - './data/geoserver/data_dir/:/opt/geoserver/data_dir'
    depends_on:
      - postgis
    restart: on-failure

  wmsclient:
    image: 'nginx:1.21.3-alpine'
    hostname: wmsclient
    volumes:
      - './data/nginx/html:/usr/share/nginx/html'
    ports:
      - "80:80"
    restart: on-failure

  postgis:
    image: 'kartoza/postgis:12.1'
    hostname: postgis
    container_name: osm-geoserver-postgis_postgis
    env_file:
      - ./postgis.env
    volumes:
      - 'pgdata:/var/lib/postgresql'
    expose:
      - '5432'
    restart: on-failure

  imposm-worker:
    image: 'geotekne/imposm-worker:1.0.0'
    hostname: imposm-worker
    environment:
      - PARAMETERS=-i /pbfs -c osm-geoserver-postgis_postgis -v 12.1 -p 5432 -u docker -w docker -d gis
    volumes:
      - './pbfs/:/pbfs'
    depends_on:
      - postgis

volumes: 
     pgdata:
